server:
  port: 8087
spring:
  application:
    name: page-ribbon
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka/
