server:
  port: 8085
spring:
  application:
    name: service-flower
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mybasit?serverTimezone=GMT%2B8
    username: root
    password: 123123
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka/
mybatis:
  type-aliases-package: com.springcloud.flower.bean
  mapper-locations: classpath:/mapper/*.xml
