server:
  port: 8086
spring:
  application:
    name: service-page
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8080/eureka/